spring:
  application:
    name: produit
  datasource:
    url: jdbc:postgresql://localhost:5432/produit
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false